# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='f_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
