# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0002_food_f_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=512)),
                ('owner_name', models.CharField(max_length=200)),
                ('office', models.CharField(max_length=32)),
                ('arrival_time', models.TimeField(verbose_name='Arrival Time')),
            ],
        ),
        migrations.DeleteModel(
            name='Food',
        ),
    ]
