# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiter', '0004_auto_20170720_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(default='example@example.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
